name: PerceptWatch
options:
  bundleIdPrefix: com.percept
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: 57KP67PPR6
    CODE_SIGN_STYLE: Automatic

targets:
  PerceptCompanion:
    type: application
    platform: iOS
    sources:
      - path: PerceptCompanion
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.percept.companion
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
    info:
      path: PerceptCompanion/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
        BGTaskSchedulerPermittedIdentifiers:
          - com.percept.companion.refresh

  PerceptWatch:
    type: application
    platform: watchOS
    sources:
      - path: PerceptWatch
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.percept.companion.watchkitapp
